SELECT
INVENTORY,--需求统计
SUPPLY_TYPE,-- 需求类型
DATA_TYPE,--已清洗和未清洗
OPEN_QTY--未清洗和已清洗QTY数据   (IN表 OPEN_QTY)
FROM
(
SELECT 'INVENTORY' AS INVENTORY ,'NOT_CLEAR' AS DATA_TYPE, 'INV' AS  SUPPLY_TYPE ,SUM(QTY) AS OPEN_QTY FROM IN_MDS_INVENTORY
LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM WHERE ATP_MATL_GROUP = '压缩机'
UNION
SELECT 'INVENTORY' AS INVENTORY ,'NOT_CLEAR' AS DATA_TYPE, 'SC1' AS SUPPLY_TYPE,SUM(NET_TRANSIT_QTY) AS OPEN_QTY FROM  IN_MDS_DELIVERY_NOTE
LEFT JOIN MID_MDS_ITEM ON MATERIAL_CODE = ITEM WHERE ATP_MATL_GROUP = '压缩机'
UNION
SELECT 'INVENTORY' AS INVENTORY ,'NOT_CLEAR' AS DATA_TYPE,'STO' AS SUPPLY_TYPE,SUM(UNCLEAR_QTY) AS OPEN_QTY FROM  IN_MDS_SUPPLY_STO
LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM WHERE ATP_MATL_GROUP = '压缩机'
UNION
SELECT 'INVENTORY' AS INVENTORY ,'NOT_CLEAR' AS DATA_TYPE,'WO' AS SUPPLY_TYPE,SUM(uninstock_qty) AS OPEN_QTY FROM  IN_MDS_PROD
LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM WHERE ATP_MATL_GROUP = '压缩机'

UNION
-- 2、已清洗的数据
SELECT 'INVENTORY' AS INVENTORY ,'CLEAR' AS DATA_TYPE,'INV' AS  SUPPLY_TYPE, SUM(QTY) AS OPEN_QTY
FROM  IN_MDS_INVENTORY_ERROR LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM
WHERE VERSION  IN (SELECT MAX(VERSION) FROM CHECK_ERROR_LOG WHERE TABLE_NAME = 'IN_MDS_INVENTORY')
AND  ATP_MATL_GROUP = '压缩机'

UNION
SELECT 'INVENTORY' AS INVENTORY ,'CLEAR' AS DATA_TYPE,'SC1' AS  SUPPLY_TYPE, SUM(NET_TRANSIT_QTY) AS OPEN_QTY
FROM  IN_MDS_DELIVERY_NOTE_ERROR LEFT JOIN MID_MDS_ITEM ON MATERIAL_CODE = ITEM
WHERE VERSION  IN (SELECT MAX(VERSION) FROM CHECK_ERROR_LOG WHERE TABLE_NAME = 'IN_MDS_DELIVERY_NOTE')
AND  ATP_MATL_GROUP = '压缩机'

UNION
SELECT 'INVENTORY' AS INVENTORY ,'CLEAR' AS DATA_TYPE,'STO' AS  SUPPLY_TYPE, SUM(UNCLEAR_QTY) AS OPEN_QTY
FROM  IN_MDS_SUPPLY_STO_ERROR LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM
WHERE VERSION  IN (SELECT MAX(VERSION) FROM CHECK_ERROR_LOG WHERE TABLE_NAME = 'IN_MDS_SUPPLY_STO')
AND  ATP_MATL_GROUP = '压缩机'

UNION
SELECT 'INVENTORY' AS INVENTORY ,'CLEAR' AS DATA_TYPE,'STO' AS  SUPPLY_TYPE, SUM(uninstock_qty) AS OPEN_QTY
FROM  IN_MDS_PROD_ERROR LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM
WHERE VERSION  IN (SELECT MAX(VERSION) FROM CHECK_ERROR_LOG WHERE TABLE_NAME = 'IN_MDS_SUPPLY_STO')
AND  ATP_MATL_GROUP = '压缩机'
)
ORDER BY SUPPLY_TYPE,DATA_TYPE