--     "压缩机供应商承诺": """
SELECT KEY_M_RC.MATERIAL_CODE                             AS ITEM,
       NVL(CFG.ATTR2, 'NO-LOC')                           AS LOC,
       KEY_M_RC.PERIOD_DATE                               AS AVAILDATE,
       TO_CHAR(PERIOD_DATE ,'YYYY-MM')                        MONTH,
       KEY_M_RC.QTY,
       'SC2#' || KEY_M_RC.SITE_CODE || '#' || KEY_M_RC.ID AS STORE,
       KEY_M_RC.SITE_CODE                                 AS PLANT,
       'SC2'                                              AS SUPPLY_TYPE
FROM SDBMGR_KT.IN_MDS_KEY_MATERIAL_RISK_COMMITMENT_DATA KEY_M_RC
         LEFT JOIN SDBMGR_KT.IN_MDS_CFG_PARAMETER CFG
                   ON CFG.BELONG_DOMAIN = 'ALL'
                       AND CFG.PARAM_NAME = 'SAP_ATP_LOC_MAPPING'
                       AND CFG.ATTR1 = 'Y'
                       AND CFG.DIMENSION1 = KEY_M_RC.SITE_CODE
WHERE KEY_M_RC.SIMULATION_NAME = 'MDS_KT'
  AND KEY_M_RC.VERSION_ID =
      (SELECT MAX(VERSION_ID)
       FROM SDBMGR_KT.IN_MDS_KEY_MATERIAL_RISK_COMMITMENT_DATA)
  AND KEY_M_RC.QTY > 0 AND QTY_TYPE = 2;


--     "压缩机供应商承诺SIM表": """
SELECT KEY_M_RC.MATERIAL_CODE                             AS ITEM,
       NVL(CFG.ATTR2, 'NO-LOC')                           AS LOC,
       KEY_M_RC.PERIOD_DATE                               AS AVAILDATE,
       TO_CHAR(PERIOD_DATE, 'YYYY-MM')                        MONTH,
       KEY_M_RC.QTY,
       'SC2#' || KEY_M_RC.SITE_CODE || '#' || KEY_M_RC.ID AS STORE,
       KEY_M_RC.SITE_CODE                                 AS PLANT,
       'SC2'                                              AS SUPPLY_TYPE
FROM SDBMGR_KT.IN_MDS_KEY_MATERIAL_RISK_COMMITMENT_DATA KEY_M_RC
         LEFT JOIN SDBMGR_KT.IN_MDS_CFG_PARAMETER CFG
                   ON CFG.BELONG_DOMAIN = 'ALL'
                       AND CFG.PARAM_NAME = 'SAP_ATP_LOC_MAPPING'
                       AND CFG.ATTR1 = 'Y'
                       AND CFG.DIMENSION1 = KEY_M_RC.SITE_CODE
WHERE KEY_M_RC.SIMULATION_NAME = 'MDS_KT'
  AND KEY_M_RC.VERSION_ID =
      (SELECT MAX(VERSION_ID)
       FROM SDBMGR_KT.IN_MDS_KEY_MATERIAL_RISK_COMMITMENT_DATA)
  AND KEY_M_RC.QTY > 0 AND QTY_TYPE = 2;



SELECT
SEQNUM,
SUPPLYSEQNUM ,
SUPPLYLOC, --产能地点
RESTYPE, --产能类型
RES, --资源
b.PHYSICAL_ADDR,
WHENLOADED,-- 产能时间
DMDPEGQTY --产能数量
FROM TMP_MDS_MATERIAL_PEGGING a
    left join IN_MDS_TWO_DEVICES_CAPACITY_INFO_HEADER b
on a.RESNAME = b.UNITE_SPEC || b.BASE
WHERE CAPACITY NOT IN (99999999,999999999,0) AND  RESTYPE = '模具产能'

  and b.PHYSICAL_ADDR is not null
  AND seqNUM = '1678914' ;

select RESNAME,UNITESPEC from TMP_MDS_MATERIAL_PEGGING
    WHERE CAPACITY NOT IN (99999999,999999999,0) AND  RESTYPE = '两器产能'  ;





SELECT
    SITE_ID,        --工厂
    SUM(OPEN_QTY) --未清洗QTY数据   (IN表 OPEN_QTY)
FROM
(
    SELECT SITE_ID, SUM(QTY) AS OPEN_QTY FROM IN_MDS_INVENTORY imi
    LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM WHERE ATP_MATL_GROUP = '压缩机' GROUP BY SITE_ID
    UNION
    SELECT SITE_CODE,SUM(NET_TRANSIT_QTY) AS OPEN_QTY FROM  IN_MDS_DELIVERY_NOTE
    LEFT JOIN MID_MDS_ITEM ON MATERIAL_CODE = ITEM WHERE ATP_MATL_GROUP = '压缩机' GROUP BY SITE_CODE
    UNION
    SELECT FACTORY_NO,SUM(UNCLEAR_QTY) AS OPEN_QTY FROM  IN_MDS_SUPPLY_STO
    LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM WHERE ATP_MATL_GROUP = '压缩机' GROUP BY FACTORY_NO
    UNION
    SELECT FACTORY_NO,SUM(uninstock_qty) AS OPEN_QTY FROM  IN_MDS_PROD
    LEFT JOIN MID_MDS_ITEM ON MATERIAL_NO = ITEM WHERE ATP_MATL_GROUP = '压缩机' GROUP BY FACTORY_NO
)
GROUP BY SITE_ID;